### ISSUE TITLE
Flannel does not clean up stale wireguard peers

### ISSUE THREAD

**Issue by nabam** [k3s-io/k3s#5216]
**Environmental Info:**
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10
flannel version v0.12.0-k3s2

Node(s) CPU architecture, OS, and Version: 
Linux eg-e0-dc-a0-65-f2-47 5.4.143-intel-pk-standard #1 SMP PREEMPT Thu Sep 23 11:38:48 UTC 2021 x86_64 GNU/Linux

Cluster Configuration:
flannel with wireguard backend (`--flannel-backend=wireguard`)
3 servers, 198 agents

**Describe the bug:**

Flannel does not clean up old wireguard peers when topology changes. Not sure if this issue should be addressed by k3s or flannel. 

Every time k3s agent restarts on one of the agents, flannel regenerates wireguard key and propagates it to all nodes in the mesh, new wireguard peers are configured with updated key, but old ones stay in the wireguard table forever with empty "allowed ips". On some of our clusters with dynamic topology I counted tens of thousands stale peers. On large L2 domains that behaviour causes storm of ARP requests from online agents towards nodes that were shut down. We were able to work around the issue with a shell script that cleans up dead peers every minute:
```
          while true; do
            for peer in $(wg show flannel.1 allowed-ips | grep '(none)' | cut -f1); do
              echo wg set flannel.1 peer $peer remove;
              wg set flannel.1 peer $peer remove;
            done;
            sleep 60;
          done
``` 

**Steps To Reproduce:**

- pick two k3s nodes (10.100.0.242 and 10.100.248.21 in my example)
- on the first node find wireguard peers pointing to the second one:
```
10.100.0.242# wg show flannel.1 | grep -A3 -B1 10.100.248.21
peer: AH54gr/ju66X9URAJsd0vRlcC39KyLPzd4dih6Tfai8=
  endpoint: 10.100.248.21:51820
  allowed ips: 10.4.7.128/26
  transfer: 23.10 MiB received, 14.38 MiB sent
  persistent keepalive: every 25 seconds
```
- restart k3s-agent on the second node:
```
10.100.248.21# systemctl restart k3s-agent
```
- check wireguard configuration on the first node:
```
10.100.0.242# wg show flannel.1 | grep -A3 -B1 10.100.248.21
peer: AH54gr/ju66X9URAJsd0vRlcC39KyLPzd4dih6Tfai8=
  endpoint: 10.100.248.21:51820
  allowed ips: (none)
  transfer: 23.10 MiB received, 14.38 MiB sent
  persistent keepalive: every 25 seconds
--
peer: DVE5Kxd0q3fZcsyi778x5R5oRIjtsFG0Cy4seoDXSQg=
  endpoint: 10.100.248.21:51820
  allowed ips: 10.4.7.128/26
  transfer: 148 B received, 240 B sent
  persistent keepalive: every 25 seconds
```

**Expected behavior:**
Old peer should be removed

**Actual behavior:**
Old peer stays in the wireguard table forever

**Additional context / logs:**

`10.100.0.242`:
```
Mar 07 13:19:34 k3s[328]: I0307 13:19:34.299309     328 extension_network.go:77] Subnet added: 10.4.7.128/26 via 10.100.248.21
Mar 07 13:19:34 k3s[328]: I0307 13:19:34.308912     328 extension_network.go:103] Ran command: read PUBLICKEY; wg set flannel.1 peer $PUBLICKEY endpoint $PUBLIC_IP:51820 allowed-ips $SUBNET persistent>
Mar 07 13:19:34 k3s[328]:  Output:
```
`10.100.248.21`:
```
Mar 07 13:19:33 k3s[1798856]: I0307 13:19:33.187786 1798856 flannel.go:92] Determining IP address of default interface
Mar 07 13:19:33 k3s[1798856]: I0307 13:19:33.190352 1798856 flannel.go:105] Using interface with name eno2 and address 10.100.248.21
Mar 07 13:19:34 k3s[1798856]: I0307 13:19:34.206967 1798856 extension.go:88] Ran command: wg genkey | tee privatekey | wg pubkey
Mar 07 13:19:34 k3s[1798856]:  Output: DVE5Kxd0q3fZcsyi778x5R5oRIjtsFG0Cy4seoDXSQg=
Mar 07 13:19:34 k3s[1798856]: I0307 13:19:34.540844 1798856 extension.go:126] Ran command: export SUBNET_IP=$(echo $SUBNET | cut -d'/' -f 1); ip link del flannel.1 2>/dev/null; echo $PATH >&2; wg-add.>
Mar 07 13:19:34 k3s[1798856]:  Output: /var/lib/rancher/k3s/data/e325c88e138cff20a5906e3cdef2b3a95253fd171760b01ef9277ade632df790/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/>
Mar 07 13:19:34 k3s[1798856]: I0307 13:19:34.544619 1798856 flannel.go:78] Wrote subnet file to /run/flannel/subnet.env
Mar 07 13:19:34 k3s[1798856]: I0307 13:19:34.545045 1798856 flannel.go:82] Running backend.
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
The version of Flannel in the version of K3s that you're using does not natively support wireguard; it is hacked in via the shell extension backend. When we replace this with native flannel wireguard support this issue should be resolved.

https://github.com/k3s-io/k3s/blob/44c53743dd27bce9422ebdbd59c34b7359446c95/pkg/agent/flannel/setup.go#L68-L75

Also see: 
* https://github.com/k3s-io/k3s/issues/5101#issuecomment-1034130191

**Comment by VestigeJ** [comment]
**Re-created this using VERSION=v1.21.10+k3s1, (latest (v1.22.9) COMMIT=d73772d60d3c6f320c0ff06856b46d9bd9df5817, AND (latest v1.23.5) COMMIT=c1095dd0159bdb6c619d7c0fa725c765778f0122**

I'm still seeing duplicate entries in the WireGuard Table after restarting k3s service on server nodes. Upgrading the cluster to different versions does clear this back down to the regular node count though. Most likely I'm trying to validate this incorrectly. Please advise if you see anything glaringly obvious. 

$ k3s -v
```
k3s version v1.23.5+k3s-c1095dd0 (c1095dd0)
go version go1.17.5
```

```
Every 3.0s: sudo wg show flannel.1   ip-172-31-19-156: Mon Apr 11 23:18:55 2022

interface: flannel.1
  public key: oa4cDf5qmdXhHAZTbH/RKPksl+Ywktf7IVfHhUZDiVs=
  private key: (hidden)
  listening port: 51820

peer: QUefRnNvtluaPRTqzV/t0myiANgoxgv4tHtegExdkR0=
  endpoint: 172.31.28.247:51820
  allowed ips: 10.42.1.0/24
  latest handshake: 44 seconds ago
  transfer: 12.39 KiB received, 25.37 KiB sent
  persistent keepalive: every 25 seconds

peer: 0A3qeNNPUPbZATnFcEzJbcxdXvzCzGvzW+4jDfBCwCE=
  endpoint: 172.31.29.129:51820
  allowed ips: 10.42.2.0/24
  latest handshake: 44 seconds ago
  transfer: 34.04 KiB received, 62.90 KiB sent
  persistent keepalive: every 25 seconds

peer: Oae/EdXKcoXaUrSBPae/83igLJFXIgai/+ek2jw5rlg=
  endpoint: 172.31.31.102:51820
  allowed ips: 10.42.3.0/24
  latest handshake: 57 seconds ago
  transfer: 3.05 KiB received, 3.60 KiB sent
  persistent keepalive: every 25 seconds

peer: PgcajD+34KAE/6VTte+Eii9kckq/Q1we6yta+t67gjY=
  endpoint: 172.31.28.247:51820
  allowed ips: (none)
  latest handshake: 2 minutes, 1 second ago
  transfer: 54.39 KiB received, 96.87 KiB sent
  persistent keepalive: every 25 seconds

peer: Y47Gd6mWwgt06oLiRBm+NAKAoH4FD4Q2piA2FFOexGo=
  endpoint: 172.31.29.129:51820
  allowed ips: (none)
  latest handshake: 4 minutes, 22 seconds ago
  transfer: 35.49 KiB received, 70.04 KiB sent
  persistent keepalive: every 25 seconds

peer: jUNyw+s9lWQsYl9BzaW6kZwsCQyFXe3zJvY4L1Rj8EA=
  endpoint: 172.31.29.129:51820
  allowed ips: (none)
  latest handshake: 5 minutes, 17 seconds ago
  transfer: 27.39 KiB received, 60.63 KiB sent
  persistent keepalive: every 25 seconds
```


$ k3s -v
```
k3s version v1.21.10+k3s1 (471f5eb3)
go version go1.16.10
```

k3s config: 
```
write-kubeconfig-mode: 644
debug: true
server: https://3.135.18.77:6443
token: K10443218ffdf40098ed60121274f50870e02fe47d0d8e24e176ab81af583f::server:orangeamonopitaglutenyogurt
flannel-backend: wireguard
```
## Restarted k3s on multiple server nodes to generate extra entries

```
$ Every 3.0s: sudo wg show flannel.1   ip-172-31-19-156: Mon Apr 11 22:47:35 2022
interface: flannel.1
  public key: UGYow4sNYl4vb7rYnGzv0VD6Tn2IA1UMapcoPzCGP3E=
  private key: (hidden)
  listening port: 51820

peer: Fi37EtILKVK8DFCMhac+4ltHoqA3L1k01xAXNbLaQyA=
  endpoint: 172.31.29.129:51820
  allowed ips: 10.42.2.0/24
  latest handshake: 12 seconds ago
  transfer: 192.53 KiB received, 313.73 KiB sent
  persistent keepalive: every 25 seconds

peer: rlT0RdUuTWA0w5TDFFydZeER5H65fsZnmKJeAWQdsXU=
  endpoint: 172.31.31.102:51820
  allowed ips: 10.42.3.0/24
  latest handshake: 58 seconds ago
  transfer: 68.33 KiB received, 66.26 KiB sent
  persistent keepalive: every 25 seconds

peer: cs0Z9mSkLpIfY3dz14hFQFsVlAvu66j95+kJpaWZdWM=
  endpoint: 172.31.28.247:51820
  allowed ips: 10.42.1.0/24
  latest handshake: 1 minute, 20 seconds ago
  transfer: 352.03 KiB received, 600.90 KiB sent
  persistent keepalive: every 25 seconds

peer: zikRoDlpfFaw7mefKYx2kCPxsNtpcUdiQzyFB1DLthc=
  endpoint: 172.31.29.129:51820
  allowed ips: (none)
  latest handshake: 33 minutes, 44 seconds ago
  transfer: 108.63 KiB received, 213.80 KiB sent
  persistent keepalive: every 25 seconds

peer: naWutAqyelQdHe4MPlQwZQqr56ZXe8QK3mySw5sHVzE=
  endpoint: 172.31.29.129:51820
  allowed ips: (none)
  latest handshake: 52 minutes, 3 seconds ago
  transfer: 84.73 KiB received, 220.24 KiB sent
  persistent keepalive: every 25 seconds

peer: TpVXOaUrk/bQT9FMHFWRGQfLodX9647EUft7LidVQF4=
  endpoint: 172.31.29.129:51820
  allowed ips: (none)
  latest handshake: 1 hour, 3 minutes, 42 seconds ago
  transfer: 100.96 KiB received, 260.29 KiB sent
  persistent keepalive: every 25 seconds

peer: P+87tB9Dpogt20hUvbdPTJWoBz8j4rFvgOiDatvnwzw=
  endpoint: 172.31.28.247:51820
  allowed ips: (none)
  latest handshake: 1 hour, 4 minutes, 39 seconds ago
  transfer: 33.24 KiB received, 141.27 KiB sent
  persistent keepalive: every 25 seconds

peer: cutTFAdBJSIQJpmVY1aSia4K72pdbS9Kp7wYT4l8mRo=
  endpoint: 172.31.28.247:51820
  allowed ips: (none)
  latest handshake: 1 hour, 6 minutes, 45 seconds ago
  transfer: 89.75 KiB received, 257.42 KiB sent
  persistent keepalive: every 25 seconds
```

**Comment by ShylajaDevadiga** [comment]
Validated using k3s version v1.23.5+k3s-3307d53f on a two node cluster with one server one agent having wireguard-native as flannel-backend
```
$ cat config.yaml 
flannel-backend: wireguard-native
write-kubeconfig-mode: 644
token: "testsecret"
node-ip: 192.168.19.85,2600:<REDACTED>
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
disable-network-policy: true
flannel-ipv6-masq: true
```

```
sudo wg show
interface: flannel-wg
  public key: C7rwddHmEj67tJxHGU/BbQl+WtczEUbhp/6iDmd+lCI=
  private key: (hidden)
  listening port: 51820

peer: 8FrPI+hkRuxBTaTI2B95NS/oe3gyuWvlmbRv6cC4tjE=
  endpoint: 192.168.31.221:51820
  allowed ips: 10.42.1.0/24
  latest handshake: 37 seconds ago
  transfer: 180 B received, 304 B sent
  persistent keepalive: every 25 seconds

interface: flannel-wg-v6
  public key: C7rwddHmEj67tJxHGU/BbQl+WtczEUbhp/6iDmd+lCI=
  private key: (hidden)
  listening port: 51821

peer: 8FrPI+hkRuxBTaTI2B95NS/oe3gyuWvlmbRv6cC4tjE=
  endpoint: [2600:<REDACTED>]:51821
  allowed ips: 2001:cafe:42:1::/64
  latest handshake: 37 seconds ago
  transfer: 180 B received, 304 B sent
  persistent keepalive: every 25 seconds
```
After restarting agent node no extra entries with `allowed ips: (none)` are present
```
ubuntu@ip-192-168-19-85:~$ sudo wg show
interface: flannel-wg
  public key: C7rwddHmEj67tJxHGU/BbQl+WtczEUbhp/6iDmd+lCI=
  private key: (hidden)
  listening port: 51820

peer: 8FrPI+hkRuxBTaTI2B95NS/oe3gyuWvlmbRv6cC4tjE=
  endpoint: 192.168.31.221:51820
  allowed ips: 10.42.1.0/24
  latest handshake: 1 second ago
  transfer: 360 B received, 428 B sent
  persistent keepalive: every 25 seconds

interface: flannel-wg-v6
  public key: C7rwddHmEj67tJxHGU/BbQl+WtczEUbhp/6iDmd+lCI=
  private key: (hidden)
  listening port: 51821

peer: 8FrPI+hkRuxBTaTI2B95NS/oe3gyuWvlmbRv6cC4tjE=
  endpoint: [2600:<REDACTED>]:51821
  allowed ips: 2001:cafe:42:1::/64
  latest handshake: 1 second ago
  transfer: 360 B received, 428 B sent
  persistent keepalive: every 25 seconds
ubuntu@ip-192-168-19-85:~$ 
```
