### ISSUE TITLE
Unable to restart HA cluster after etcd size limit reached

### ISSUE THREAD

**Issue by ssmall** [k3s-io/k3s#5331]
Please see logs and additional context in https://github.com/k3s-io/k3s/issues/4787#issuecomment-1071901452

__Originally posted by @ssmall in https://github.com/k3s-io/k3s/issues/4787#issuecomment-1077880193__

To summarize the history and remaining issue, since the previous issue seems to have gotten conflated with a couple different problems:
- I have a 3-master, 4-worker HA k3s cluster that went down and began failing to start up on 12 Feb with the error `panic: etcdserver: mvcc: database space exceeded` (https://github.com/k3s-io/k3s/issues/4787#issuecomment-1037652836)

- Following the advice of @brandond I added `--etcd-arg=quota-backend-bytes=$((8*1024*1024*1024))` to the startup args for my master nodes (https://github.com/k3s-io/k3s/issues/4787#issuecomment-1039493992)

- I also tried pointing a stand-alone etcd at the db directory, however that did not resolve the issue with k3s startup (https://github.com/k3s-io/k3s/issues/4787#issuecomment-1066218285)

- Tried a couple fixes provided by @brandond and got a bit farther, however now as soon as I bring up the second master node and the two nodes start talking to each other, it’s back to the original error (https://github.com/k3s-io/k3s/issues/4787#issuecomment-1071083112)

**Comment by ssmall** [comment]
Please do let me know if there is any more information I can provide to help investigate this issue. At this point my cluster has been completely down for over a month and there does not appear to be any workaround available to bring it back up. The only option appears to be to rebuild the cluster from scratch, and if I end having to go that route I will need to switch to a different k8s distro lest I end up back in the same situation.

**Comment by brandond** [comment]
We're unable to reproduce this on our end, either by filling the datastore or by artificially lowering the quota and then subsequently raising it. Your logs show that the alarms have been cleared so I'm not sure why it's still returning space errors.

The etcd docs do note one thing that we're not doing:
> If the keyspace’s backend database for any member exceeds the space quota, etcd raises a cluster-wide alarm that puts the cluster into a maintenance mode which only accepts key reads and deletes. Only after freeing enough space in the keyspace **and defragmenting the backend database**, along with clearing the space quota alarm can the cluster resume normal operation.

I'll open a PR to add that, lets see if that resolves your issue.

**Comment by ssmall** [comment]
Oh, good find. That might actually help explain the behavior I'm now seeing. I experimented with the standalone etcd on one of the master nodes, and may have triggered defragmentation as part of that process. That node is able to start up, but when the next node tries to start up (having not had anything done to its etcd db since the issue first started occurring) it seems to be raising the cluster-wide alarm again.

I will try pointing a stand-alone etcd at the db directory of the second node to see if it fixes the k3s startup issues.

**Comment by brandond** [comment]
That PR doesn't quite work yet. I'm still tinkering with it. You might have some luck defragging and then clearing the alarms using the etcd binary though.

**Comment by brandond** [comment]
That PR build should work now; try with `INSTALL_K3S_COMMIT=e29068294fb43dd0c2b168277791eb17df5bfbb7`

**Comment by ssmall** [comment]
I decided to try the PR build you provided first before experimenting with standalone etcd on the second node. The PR build does not appear to have resolved the problem, unfortunately. Both nodes are still failing to start up with `panic: etcdserver: mvcc: database space exceeded`, however this still only happens once I try to bring up the second node. I have attached logs for both nodes to this comment

- [k3s.antikythera.daemon.log](https://github.com/k3s-io/k3s/files/8358322/k3s.antikythera.daemon.log) -- this is the first master node, the one one which I mucked around with standalone etcd while trying to work around this issue
- [k3s.big-nuc.daemon.log](https://github.com/k3s-io/k3s/files/8358323/k3s.big-nuc.daemon.log) -- this is the second master node; I have not done anything to this one except trying the various different k3s builds that you have provided

Next I will try pointing a standalone etcd at `/var/lib/rancher/k3s/server/db` on the second master (`big-nuc`) and see what happens.

**Comment by ssmall** [comment]
Also tried pointing a standalone etcd at `/var/lib/rancher/k3s/server/db` on the second master and that does not appear to have helped. I tried the steps provided at https://etcd.io/docs/v3.4/op-guide/maintenance/#space-quota but k3s still fails to start up with the same error when I attempt to join the second node to the cluster.

For what it's worth, I also tried switching the order in which I start the nodes and the behavior is the same. The first node to start up does so successfully and waits for another node to join, then when the second node starts up they both fail with `panic: etcdserver: mvcc: database space exceeded`

**Comment by brandond** [comment]
Hmm. Whatever state you've gotten into, we can't seem to reproduce it, and the steps that should be fixing it are not. Would you be willing to provide us with a copy of /var/lib/rancher/k3s/server from all three of your nodes?

**Comment by ssmall** [comment]
> Would you be willing to provide us with a copy of /var/lib/rancher/k3s/server from all three of your nodes? 

Yes I can do that, however I'm not going to be able to upload it to GitHub because there is data in there that should not be public. Is there a way I can share it with you securely?

**Comment by brandond** [comment]
Do you have a Dropbox or Google Drive link you could send to me via email? brad.davidson@rancher.com

**Comment by ssmall** [comment]
I just sent you a Google Drive link to two tarballs of the entire /var/lib/rancher/k3s/server directories on two of my three master nodes. I'm only able to include two at the moment because the third node actually got taken offline by this issue and I haven't been able to bring it back up -- I suspect that when it tries to start up k3s on boot, something is getting saturated and I'm unable to SSH to it. It's the most resource-constrained of the three and I was about to replace it anyway, so I just took it offline completely when this issue started happening.

Please let me know if there is more that you need from me to investigate this issue! I would also be happy to set up a video call to do live debugging and give you direct access to the hosts if that would be helpful.

**Comment by brandond** [comment]
>  I'm only able to include two at the moment because the third node actually got taken offline by this issue and I haven't been able to bring it back up

Ahh see, that would be why. The datastore won't accept writes until alarms are cleared on all the cluster members, and you haven't brought that 3rd member online. 

> {"level":"info","ts":"2022-03-28T06:41:42.727Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"fcfb4c91f4fc885c switched to configuration voters=(4601869108914463604 9791417851272883171 18229248106476374108)"}
time="2022-03-28T06:43:07Z" level=info msg="Local etcd datastore using 31739904 of 31756288 bytes; errors: [memberID:4601869108914463604 alarm:NOSPACE ]"

Member `4601869108914463604` is that third node that you haven't brought back online.  I'm not sure if I recommended  this already, but you should start up the first node with `--cluster-reset`, then add the remaining servers - assuming you haven a 3rd server to replace the missing one with, since running etcd with just 2 servers is a bad idea.

I'll probably modify the PR to block if there are any errors on the datastore, rather than continuing on and crashing as it currently does.

**Comment by brandond** [comment]
```
root@ubuntu01:~# kubectl get nodes -o wide
NAME          STATUS     ROLES                       AGE    VERSION                INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION           CONTAINER-RUNTIME
antikythera   Ready      control-plane,etcd,master   130d   v1.23.5+k3s-ac6325b7   192.168.1.33   <none>        Ubuntu 21.10                     5.14.13-051413-generic   containerd://1.5.10-k3s1
big-nuc       Ready      control-plane,etcd,master   315d   v1.23.5+k3s-ac6325b7   192.168.1.31   <none>        Ubuntu 21.10                     5.14.13-051413-generic   containerd://1.5.10-k3s1
liva-x        Ready      <none>                      315d   v1.22.5+k3s1           192.168.1.32   <none>        Debian GNU/Linux 10 (buster)     4.19.0-18-amd64          containerd://1.5.8-k3s1
monolith      NotReady   control-plane,etcd,master   165d   v1.22.5+k3s1           192.168.1.62   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-10-amd64          containerd://1.5.8-k3s1
nuccy         Ready      <none>                      129d   v1.22.5+k3s1           192.168.1.30   <none>        Debian GNU/Linux 10 (buster)     4.19.0-18-amd64          containerd://1.5.8-k3s1
pumpkin-pi    Ready      <none>                      319d   v1.22.5+k3s1           192.168.1.20   <none>        Debian GNU/Linux 10 (buster)     5.10.63-v8+              containerd://1.5.8-k3s1
rastau        Ready      <none>                      476d   v1.22.5+k3s1           192.168.1.71   <none>        Ubuntu 18.04.6 LTS               5.3.0-1042-raspi2        containerd://1.5.8-k3s1

Try with `INSTALL_K3S_COMMIT=ac6325b74f68fa3554c7270dbe9da74da68f28b8`
```

**Comment by ssmall** [comment]
That got a lot farther! I'm seeing what you're seeing from `kubectl get nodes` but it looks like the master nodes themselves are stuck in a loop trying to activate. I tried adding a third master node to replace `monolith` (the previous third master that died) and it failed with the following logs:

```
Mar 28 23:55:19 beelink-one k3s[153327]: time="2022-03-28T23:55:19-07:00" level=info msg="Adding member beelink-one-b3281864=https://192.168.1.34:2380 to etcd cluster [monolith-da989511=https://192.168.1.62:2380 big-nuc-8337f722=https://192.168.1.31:2380 antikythera-0948c62a=https://192.168.1.33:2380]"
Mar 28 23:55:19 beelink-one k3s[153327]: {"level":"warn","ts":"2022-03-28T23:55:19.181-0700","logger":"etcd-client","caller":"v3@v3.5.1-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00155c380/192.168.1.62:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: unhealthy cluster"}
Mar 28 23:55:19 beelink-one k3s[153327]: time="2022-03-28T23:55:19-07:00" level=fatal msg="ETCD join failed: etcdserver: unhealthy cluster"
```

**Comment by brandond** [comment]
Did you use `kubectl delete node` to remove the failed server from the cluster? Until you do that, or reset the cluster back to 1 node with --cluster-reset, your cluster will be stuck with 2/3 members. Adding a 4th member would put you temporarily at 2/4 as the new node joins, which does not meet quorum requirements and is therefore not allowed by etcd. You can only join a new node when all existing members are healthy.

**Comment by ssmall** [comment]
I tried `kubectl delete node` but it just hangs indefinitely without actually removing the node. Did that work when you tried it? It seems like etcd is still read-only.

**Comment by ssmall** [comment]
> Until you do that, or reset the cluster back to 1 node with --cluster-reset, your cluster will be stuck with 2/3 members.

Does `--cluster-reset` completely wipeout etcd? Or just forget the other etcd members? I definitely want to avoid fully resetting my cluster otherwise I will have start again from scratch.

**Comment by brandond** [comment]
The datatore isn't read-only, if it was then Kubernetes wouldn't be running. I was able to delete the member from the cluster without any issues, although it did take a moment for the command to complete and the log spam from etcd to subside:

```console
root@ubuntu01:~# kubectl get nodes -o wide
NAME          STATUS     ROLES                       AGE    VERSION                INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION           CONTAINER-RUNTIME
antikythera   Ready      control-plane,etcd,master   131d   v1.23.5+k3s-ac6325b7   192.168.1.33   <none>        Ubuntu 21.10                     5.14.13-051413-generic   containerd://1.5.10-k3s1
big-nuc       Ready      control-plane,etcd,master   316d   v1.23.5+k3s-ac6325b7   192.168.1.31   <none>        Ubuntu 21.10                     5.14.13-051413-generic   containerd://1.5.10-k3s1
liva-x        Ready      <none>                      316d   v1.22.5+k3s1           192.168.1.32   <none>        Debian GNU/Linux 10 (buster)     4.19.0-18-amd64          containerd://1.5.8-k3s1
monolith      NotReady   control-plane,etcd,master   166d   v1.22.5+k3s1           192.168.1.62   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-10-amd64          containerd://1.5.8-k3s1
nuccy         Ready      <none>                      131d   v1.22.5+k3s1           192.168.1.30   <none>        Debian GNU/Linux 10 (buster)     4.19.0-18-amd64          containerd://1.5.8-k3s1
pumpkin-pi    Ready      <none>                      320d   v1.22.5+k3s1           192.168.1.20   <none>        Debian GNU/Linux 10 (buster)     5.10.63-v8+              containerd://1.5.8-k3s1
rastau        Ready      <none>                      477d   v1.22.5+k3s1           192.168.1.71   <none>        Ubuntu 18.04.6 LTS               5.3.0-1042-raspi2        containerd://1.5.8-k3s1

root@ubuntu01:~# kubectl delete node monolith
node "monolith" deleted

root@ubuntu01:~# kubectl get nodes -o wide
NAME          STATUS   ROLES                       AGE    VERSION                INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION           CONTAINER-RUNTIME
antikythera   Ready    control-plane,etcd,master   131d   v1.23.5+k3s-ac6325b7   192.168.1.33   <none>        Ubuntu 21.10                   5.14.13-051413-generic   containerd://1.5.10-k3s1
big-nuc       Ready    control-plane,etcd,master   316d   v1.23.5+k3s-ac6325b7   192.168.1.31   <none>        Ubuntu 21.10                   5.14.13-051413-generic   containerd://1.5.10-k3s1
liva-x        Ready    <none>                      316d   v1.22.5+k3s1           192.168.1.32   <none>        Debian GNU/Linux 10 (buster)   4.19.0-18-amd64          containerd://1.5.8-k3s1
nuccy         Ready    <none>                      131d   v1.22.5+k3s1           192.168.1.30   <none>        Debian GNU/Linux 10 (buster)   4.19.0-18-amd64          containerd://1.5.8-k3s1
pumpkin-pi    Ready    <none>                      320d   v1.22.5+k3s1           192.168.1.20   <none>        Debian GNU/Linux 10 (buster)   5.10.63-v8+              containerd://1.5.8-k3s1
rastau        Ready    <none>                      477d   v1.22.5+k3s1           192.168.1.71   <none>        Ubuntu 18.04.6 LTS             5.3.0-1042-raspi2        containerd://1.5.8-k3s1
```

`--cluster-reset` just resets the etcd cluster membership to a single node. It does not remove any data from the datastore itself.

**Comment by ssmall** [comment]
Could you provide explicit steps to follow to restore the cluster to a working state? I've been trying what you have suggested in comments, but there must be something I am missing because I am not able to actually bring my cluster back to a working state. Setting the `--cluster-reset` flag does not appear to have had any effect.

**Comment by brandond** [comment]
All I did was start a server using the files from `antikythera`, and another server using the files from `big-nuc`. Once Kubernetes was up, I issued a `kubectl delete node monolith` and then waited about a minute. Another minute or so after that command completed, the log messages from etcd about not being able to communicate with that node stopped. If your nodes have a lot going on (due to all the various pods and agent nodes being up) it might take a bit longer due to datastore load.

If you are **instead** going to do a cluster-reset, you should make sure that all the other nodes in the cluster are stopped as well. Start up with the --cluster-reset flag on the first server, then follow the instructions to remove the datastore from the other servers before starting them up again, which will rejoin them to the cluster. After that's done, start up the agents.

**Comment by ssmall** [comment]
I have tried both of the ways you just described and the behavior is the same -- `kubectl delete node/monolith` hangs indefinitely. So I'm not sure where to go from here. Maybe there is some difference between my machine and the machine you're reproducing the issue on that is causing different behavior?

**Comment by brandond** [comment]
I can't say what's different about your environment, but either operation should be pretty cut and dried at this point. I have been able to repeat the steps several times after copying out the contents of the tarballs you sent me.

If you've completed the cluster-reset operation then `monolith` is no longer in the etcd cluster; you can just `kubectl edit node monolith` and delete the `wrangler.cattle.io/managed-etcd-controller` finalizer entry, which is probably what's blocking the delete for whatever reason, and then delete the node.

**Comment by ssmall** [comment]
So, even in the output you've provided from your repro, all the other nodes show as `Ready` -- surely this is an indicator that something is not working, right? If the cluster reset worked and k3s is coming up successfully, shouldn't the status of the other nodes be `NotReady`?

Everything that I am observing looks as if k3s is having some serious issues still. Just because the api server is running does not mean that the cluster is healthy. I am seeing tons of log lines like

```
Mar 30 20:35:34 antikythera k3s[2688162]: W0330 20:35:34.749281 2688162 reflector.go:324] storage/cacher.go:/secrets: failed to list *core.Secret: illegal base64 data at input byte 3
Mar 30 20:35:34 antikythera k3s[2688162]: E0330 20:35:34.749358 2688162 cacher.go:424] cacher (*core.Secret): unexpected ListAndWatch error: failed to list *core.Secret: illegal base64 data at input byte 3; reinitializing...
Mar 30 20:35:34 antikythera k3s[2688162]: E0330 20:35:34.916073 2688162 status.go:71] apiserver received an error that is not an metav1.Status: 3: illegal base64 data at input byte 3
Mar 30 20:35:34 antikythera k3s[2688162]: W0330 20:35:34.917196 2688162 reflector.go:324] k8s.io/client-go@v1.23.5-k3s1/tools/cache/reflector.go:167: failed to list *v1.Secret: illegal base64 data at input byte 3
Mar 30 20:35:34 antikythera k3s[2688162]: E0330 20:35:34.917249 2688162 reflector.go:138] k8s.io/client-go@v1.23.5-k3s1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: illegal base64 data at input byte 3
Mar 30 20:35:35 antikythera k3s[2688162]: E0330 20:35:35.053490 2688162 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"00d4c363-1c49-4e64-ac87-f62b7ccfdfcc\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=21
Mar 30 20:35:35 antikythera k3s[2688162]: W0330 20:35:35.898739 2688162 reflector.go:324] storage/cacher.go:/secrets: failed to list *core.Secret: illegal base64 data at input byte 3
Mar 30 20:35:35 antikythera k3s[2688162]: E0330 20:35:35.898823 2688162 cacher.go:424] cacher (*core.Secret): unexpected ListAndWatch error: failed to list *core.Secret: illegal base64 data at input byte 3; reinitializing...
Mar 30 20:35:36 antikythera k3s[2688162]: I0330 20:35:36.028570 2688162 scope.go:110] "RemoveContainer" containerID="2e7237ac2932d4cd25085011e78e109ba76248398b58e17dea286b52254dad11"
Mar 30 20:35:36 antikythera k3s[2688162]: E0330 20:35:36.055778 2688162 remote_runtime.go:209] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"c79ed430d70b319406b6746c5f9ebe3888651cd7f8c042ceded914683df7ed93\": open /run/flannel/subnet.env: no such file or directory"
Mar 30 20:35:36 antikythera k3s[2688162]: E0330 20:35:36.055835 2688162 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"c79ed430d70b319406b6746c5f9ebe3888651cd7f8c042ceded914683df7ed93\": open /run/flannel/subnet.env: no such file or directory" pod="longhorn-system/csi-resizer-5dc4d66566-tzzrf"
Mar 30 20:35:36 antikythera k3s[2688162]: E0330 20:35:36.055863 2688162 kuberuntime_manager.go:833] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"c79ed430d70b319406b6746c5f9ebe3888651cd7f8c042ceded914683df7ed93\": open /run/flannel/subnet.env: no such file or directory" pod="longhorn-system/csi-resizer-5dc4d66566-tzzrf"
```

These are printing over and over in the logs. Meanwhile, the results actually being returned by the API server seem stale at best -- pods are marked as `Running` on worker nodes that are no longer joined to the cluster.

**Comment by brandond** [comment]
Those messages would indicate that you had at one point run k3s with --the secrets-encryption flag but are not currently doing so. Did you remove that flag for some reason?

The nodes are showing ready because they were ready when the datastore was last used, and I didn't leave the cluster running long enough for the controller manager to notice their lack of heartbeat and update their status.

Can we get back to the etcd cluster? Did you get it reset or not?

**Comment by ssmall** [comment]
> Those messages would indicate that you had at one point run k3s with the --secrets-encryption flag but are not currently doing so. Did you remove that flag for some reason? I used that flag when starting up your cluster on my end, since there was secrets encryption configuration present in the database.

I had an issue with that previously in https://github.com/k3s-io/k3s/issues/4838 but it was resolved some time before the etcd issue started occurring.

What about the messages like

```
Mar 30 20:35:36 antikythera k3s[2688162]: E0330 20:35:36.055778 2688162 remote_runtime.go:209] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"c79ed430d70b319406b6746c5f9ebe3888651cd7f8c042ceded914683df7ed93\": open /run/flannel/subnet.env: no such file or directory"
```

Those don't have anything to do with secrets encryption, do they?
 
> Can we get back to the etcd cluster? Did you get it reset or not?

I'm not sure how to answer that. I tried to reset it following the steps you provided, exactly as detailed in https://github.com/k3s-io/k3s/issues/5331#issuecomment-1082563714. I was also able to manually remove `monolith` by removing the finalizers and then doing `kubectl delete node/monolith`. As far as I can tell, etcd is functioning again but the cluster as a whole is still unusable due to the issues mentioned above.

**Comment by ssmall** [comment]
>  I used that flag when starting up your cluster on my end, since there was secrets encryption configuration present in the database.

Looks like you edited after I after I had drafted my reply. Thanks for clarifying, I will try starting up with that flag.

**Comment by ssmall** [comment]
Aha! Adding the `--secrets-encryption` flag back was indeed the final missing piece. The cluster appears to be restored to working order now. Thanks for all your patience and responsiveness. It is great to have finally restored the cluster to working order.
