### ISSUE TITLE
PostgreSQL database become very slow

### ISSUE THREAD

**Issue by zdzichu** [k3s-io/k3s#9256]
**Environmental Info:**
K3s Version: k3s version v1.28.5+k3s1 (5b2d1271)
go version go1.20.12

Node(s) CPU architecture, OS, and Version: 

Linux kaitain.pipebreaker.pl 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024 x86_64 GNU/Linux
servers on Fedora 39, nodes on F39 and F40.

Cluster Configuration:

2 servers, 6 nodes. Using external PostgreSQL database (postgresql-15.4-1.fc39.x86_64)
Cluster running for a bit over 3 years, as a homelab. `system-upgrade-controller` tuned to `stable` channel.

**Describe the bug:**

Cluster was running OK, but recently queries against kine `k3s` database in postgres become very slow. Communication with servers using `kubectl` often fails with timeouts. There are many "Slow SQL queries" in logs.

If I run first of the slow sql queries through pg_cli's EXPLAIN, this is slowest part:
```
│   │       └─⌠ Seq Scan slowest largest
│   │         │ Finds relevant records by sequentially scanning the input record set. When reading
│   │         │ from a table, Seq Scans (unlike Index Scans) perform a single read operation (only
│   │         │ the table is read).
│   │         │ ○ Duration: 12.10 s (100%)
│   │         │ ○ Cost: 134,396 (100%)
│   │         │ ○ Rows: 1
│   │         │   on public.kine
│   │         │   filter ((mkv.name)::text ~~ '/bootstrap/%'::text) [-990,187 rows]
│   │         │   rows Overestimated by 30.00x
│   │         ⌡► mkv.name + mkv.id
```

How to optimize the database? Maybe there's some garbage collection to be done?
The base isn't very big, there are less than 1 million entries:

```
k3s> select count(*) from kine;
╒════════╕
│ count   │
╞════════╡
│ 990357  │
╘════════╛
SELECT 1
Time: 8.851s (8 seconds), executed in: 8.828s (8 seconds)
```

**Steps To Reproduce:**

- Installed K3s: 
./k3s-install server \
        --tls-san api.chi.pipebreaker.pl \
        --flannel-backend=wireguard-native
- have been using this k3s installation for over 3 years

**Expected behavior:**

Database queries should be fast.

**Actual behavior:**

**Additional context / logs:**

```
k3s[335385]: time="2024-01-16T22:48:13+01:00" level=info msg="Slow SQL (started: 2024-01-16 22:46:57.41211963 +0100 CET m=+66.649379521) (total time: 1m15.715768034s):  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE $1 GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR $2 ) AS lkv ORDER BY lkv.theid ASC  : [[/bootstrap/% false]]"

k3s[335385]: time="2024-01-16T22:48:30+01:00" level=info msg="Slow SQL (started: 2024-01-16 22:46:57.39507958 +0100 CET m=+66.632339485) (total time: 1m33.226100143s):  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE $1 GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR $2 ) AS lkv ORDER BY lkv.theid ASC LIMIT 1000 : [[/% false]]"
```

**Comment by brandond** [comment]
> Time: 8.851s (8 seconds), executed in: 8.828s (8 seconds)

It takes your postgres server almost 9 seconds just to count the rows in the table? That should be a very fast query; I'm not sure how to suggest speeding that up.

You can try stopping all your k3s servers and running a manual compaction query, but if your database is really that slow, I'm not sure that it will help long term. You can find a sample manual compact query for mysql at https://github.com/k3s-io/k3s/issues/1311#issuecomment-1308287481 - unfortunately I don't have one handy for postgres.

**Comment by zdzichu** [comment]
The database server is under serious load with 400+ connections opened by both servers (436 postgresql processes at the moment).
If I stop both k3s servers, the query is much faster:

```
k3s> select count(*) from kine;
╒═════════╕
│ count   │
╞═════════╡
│ 1108633 │
╘═════════╛
SELECT 1
Time: 0.076s
````

**Comment by brandond** [comment]
Can you perhaps scale down the workloads, stop all the K3s servers except for one, and allow it to run a compact? I suspect that compaction has fallen behind due to high load. After the server has been up for a few minutes, you should see some messages in the k3s server log regarding compaction, including how long it took and how many rows were deleted.

**Comment by zdzichu** [comment]
That's almost exactly what I've done. The issue seems resolved now.
FTR:
- I've added `--kube-controller-manager-arg leader-elect-lease-duration=10m --kube-controller-manager-arg leader-elect-renew-deadline=8m` to servers config
- downscaled most deployments
- removed some legacy namespaces
- stopped everything not critical on the DB server
- there's a number of `level=info msg="COMPACT compactRev=586242522 targetCompactRev=586243522 currentRev=586246905"; level=info msg="COMPACT deleted 1012 rows from 1000 revisions in 834.506985ms - compacted to 586243522/586246905"` statements in the log of k3s-server

After that and some waiting, the database table shrunk considerably:

```
k3s> select deleted,count(*) from kine group by deleted;
╒═════════╤═══════╕
│ deleted │ count │
╞═════════╪═══════╡
│ 0       │ 7861  │
├─────────┼───────┤
│ 1       │ 84    │
╘═════════╧═══════╛
SELECT 2
Time: 0.040s
```

Response latency is again low.

Nevertheless, it would be useful to know how to maintain the database manually if the problem arises again. For example how to trigger compaction?

Also, exposing `datastore-max-open-connections` from https://github.com/k3s-io/kine/pull/37 in k3s configuration would help in controlling the load on the DB, which right now is caused by hundreds of k3s connections.
I've tried to limit number of connections on Postgresql side. It just caused k3s to log error about exhausted connection limit, it did not throttle but tried to open another connection.

**Comment by brandond** [comment]
> exposing datastore-max-open-connections from https://github.com/k3s-io/kine/pull/37 in k3s configuration would help in controlling the load on the DB, which right now is caused by hundreds of k3s connections.

We considered doing that, but we did some actual load testing when using this option in kine and it turned out to actually make things worse. The overall delay in request processing is WORSE when kine cannot establish new connections to the database, and the connection requests go into a queue.

Excessive connections to the backend database are a SYMPTOM of a slow database, not the cause. The answer is to reduce load or improve database performance, not to place additional limits on the client.

**Comment by morzan1001** [comment]
Hi, I have a very similar problem with my k3s cluster. I also use an external postgres and 2 master nodes. The database server has 4 cores and 4 GB ram (actually enough) but meanwhile all cores are running at 100% and not enough SQL connections can be established. 

I first tried to allow more connections (from 100 to 300), which also helps the k3s server to start, but does not solve the load problem. I have switched off all workers and everything except for a master in the hope that it would then recover, but so far this has been unsuccessful. 

Is there any way to manually trigger the compact function? could I try something else?
